security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        admin_user_provider:
            entity:
                class: Wsei\Ecommerce\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: []
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADMIN.PRODUCT
            - ROLE_ADMIN.CATEGORY
            - ROLE_ADMIN.CUSTOMER
            - ROLE_ADMIN.ORDER
            - ROLE_ADMIN.CONFIG

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build|css)/
            security: false
        ecommerce_api:
            # API routes are authenticated via custom event subscriber
            pattern: ^/ecommerce/api/v1/
            stateless: true
            security: false
        main:
            lazy: true
            provider: admin_user_provider

            form_login:
                login_path: admin.login
                check_path: admin.login
                enable_csrf: true
                default_target_path: /admin/dashboard

            logout:
                path: admin.logout
                target: /admin/login

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
